### ISSUE TITLE
Odoo 11 Card Pointe/Card Connect Intergration

### ISSUE THREAD

**Issue by kast69** [mobilecause/cardconnect#13]
Odoo 11 Community is a ERP software.  I'm tring to have Card Connect tie in with Odoo however the guy i hired overseas to it is was woefully under qualified.  I believe the Card Connect API is the same, need it to work with Odoo. If you could help or point me in the right direction that would be great.

**Comment by thetizzo** [comment]
I see. I'm not sure this is the right library for your needs.  

Seems like you might just need to be able to enable the CardConnect integration Odoo has. Possibly something like this: https://www.youtube.com/watch?v=YwBUpatZeRE

Otherwise, I would go to either [CardConnect's support](https://support.cardconnect.com/) or the [Odoo forums](https://www.odoo.com/forum/help-1) to see if there are more specific examples or help for what you are trying to do.

**Comment by kast69** [comment]
It is funny you showed me that plug in.  I hired them to build that card
connect app and it does not work!  Thank you for the help. I will try odoo.

Sincerely,
Anthony Sakakeeny
978-771-9731 c
978-296-0123 o
978-475-0069 f

**Comment by thetizzo** [comment]
😂 🤦‍♂️ That figures.  I guess going with the first search result isn't always the best. 😄

**Comment by kast69** [comment]
I appreciated the geusture, it's hard to find good people. Happy codeing!

On Jul 24, 2018 5:54 PM, "Jason Taylor" <notifications@github.com> wrote:

😂 🤦‍♂️ That figures. I guess going with the first search result isn't
always the best. 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mobilecause/cardconnect/issues/13#issuecomment-407564612>,
or mute the thread
